version: '3'

services:
  db:
    image: postgres:14.6
    container_name: biblio-binder-db
    ports:
      - 54321:5432
    volumes:
      - biblio-binder-db-store:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=biblio-binder-db
      - TZ="Asia/Tokyo"
      
volumes:
  biblio-binder-db-store: